<a href="https://colab.research.google.com/github/beratkc/Rprogramlama/blob/main/3_hafta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# 22/10/2024

In [1]:
# faktör oluşturma fac() fonksiyonu
x <- factor(c("a","a","b","c","a"))
print(x)


[1] a a b c a
Levels: a b c


In [2]:
# düzey öğrenme
levels(x)

[1] "a" "b" "c"

In [5]:
# sayısal değerler
numfac<-faktor(c(3,2,2,4,1,5,5,2))

# sayısal değerler doğrudan aritmatik işlmelerde  kullanılamaz
# as.numeric ile dönüştürülür.



ERROR: Error in faktor(c(3, 2, 2, 4, 1, 5, 5, 2)): could not find function "faktor"


In [11]:
# faktöre dönüştürme vektörü
vec <- c("c","c","d","c","d")
fact <- as.factor(vec)
fact
class(fack)


[1] c c d c d
Levels: c d

[1] "factor"

In [13]:
# faktörün elamalarını erişmek ve değiştirmek
fact[3] <- "c"
# değerler için de olmayan eleman ile değişim yapılamaz!!
fact[2] <- "e"

Warning message in `[<-.factor`(`*tmp*`, 2, value = "e"):
“invalid factor level, NA generated”


In [17]:
fact <- factor(c("c","c","d","c","d"))
fact[c(3,5)]<-"c"
fact[c(3:5)]<- "c"
show(fact)


[1] c c c c c
Levels: c d


In [19]:
# yeni bir eleman ekleme
fact[6]<-"d"
show(fact)

[1] c c c c c d
Levels: c d


In [20]:
# yeni bir düzey ekleme
fat <- factor(c("a","a","b","a","b"))
levels(fat) <- c(levels(fat),"c") # c düzeyi eklendi
show(fat)

[1] a a b a b
Levels: a b c


In [29]:
levels(fat)[4]<- "d"
show(fat)


[1] a a b a b
Levels: a b c d


In [32]:
# özet
summary(fat)
# tablo ile aynı işlemi yapalım tabel()
table(fat)


a b c d 
3 2 0 0

fat
a b c d 
3 2 0 0 

In [40]:
# düzey sırası
vec <- c("alihan","efe","mert","nazlican","melda","yunus","yusuf","melih","emre","nur")
fac <- factor(vec)
fac #duzey isimleri alfabetik sira ile gelir levels

#siradaki isimleri tekrar duzenlemek istersem
yeni <- factor(fac, levels=c("mert","yunus","yusuf","alihan","nur","nurcan","emre","melih","melda","efe"))
yeni


[1] alihan   efe      mert     nazlican melda    yunus    yusuf    melih   
 [9] emre     nur     
Levels: alihan efe emre melda melih mert nazlican nur yunus yusuf

[1] alihan efe    mert   <NA>   melda  yunus  yusuf  melih  emre   nur   
Levels: mert yunus yusuf alihan nur nurcan emre melih melda efe

In [39]:
# aritmatik işlemler
fac <- factor(c(1,5,7,3,-1,2))
fac
sum(as.numeric(levels(fac)[fac])) #sayisala donusturup topladim
mean(as.numeric(levels(fac)[fac])) #sayisala donusturup ortalama alma
var(as.numeric(levels(fac)[fac])) #sayisala donusturup varyans alma

[1] 1  5  7  3  -1 2 
Levels: -1 1 2 3 5 7

[1] 17

[1] 2.833333

[1] 8.166667

In [41]:
# R da daha fazla boyutlu ornegin 3 boyutlu bir veri yapisi dizi olarak olusturulabilir
#dizi boyutlari dim() fonksiyonu ile belirlenebilir
#ornegin bir vektor biciminde tanimlanan d dizisi 2*2*3 boyutlu diziye su sekilde donusturulur
 d <- c(4,2,3,-1,0,3,3,12,8,2,14,5)
dim(d) <- c(2,2,3)
d

, , 1

     [,1] [,2]
[1,]    4    3
[2,]    2   -1

, , 2

     [,1] [,2]
[1,]    0    3
[2,]    3   12

, , 3

     [,1] [,2]
[1,]    8   14
[2,]    2    5

In [42]:
#array fonksiyonu da dizi olusturmak icin kullanilir
d <- c(4,2,3,-1,0,3,3,12,8,2,14,5)
array(d,c(2,2,3))


, , 1

     [,1] [,2]
[1,]    4    3
[2,]    2   -1

, , 2

     [,1] [,2]
[1,]    0    3
[2,]    3   12

, , 3

     [,1] [,2]
[1,]    8   14
[2,]    2    5

In [45]:
m<-matrix(c(5,3,2,2,7,1),3,2, byrow = T) #byrow satır öncelikli olsun mu T veya F
m                # satırları doldura doldura yerleştiri elamanları
# eğere byrow kullanmasaydık
mb<-matrix(c(5,3,2,2,7,1),3,2)
mb

[,1] [,2]
[1,] 5    3   
[2,] 2    2   
[3,] 7    1

[,1] [,2]
[1,] 5    2   
[2,] 3    7   
[3,] 2    1

In [47]:
#eger matris boyutu esitse tek bir boyutun tanimlanmasi yeterlidir
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
#mevcut bir matrisin boyutlarini ogrenmek icin dim()
dim(m)

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1] 3 3

In [48]:
#matris elde etmek icin matrix() fonskiyonu kullanmadan da islem yapabiliriz
#birden fazla vektor birlestirilerek de matris elde edilebilir
#vektorleri birlestirme islemini satirlara gore yapacaksak rbind()
#vektor birlestirme islemini sutunlara gore yapacaksak cbind()
#3 vektoru birlestirerek matris elde edelim

m <- cbind(c(12,26,28),c(25,13,10),c(7,9,11)) #sutunlara gore
m

m <- rbind(c(12,26,28),c(25,13,10),c(7,9,11)) #satirlara gore
m

[,1] [,2] [,3]
[1,] 12   25    7  
[2,] 26   13    9  
[3,] 28   10   11

[,1] [,2] [,3]
[1,] 12   26   28  
[2,] 25   13   10  
[3,]  7    9   11

In [51]:
#rbind() ve cbind() fonksiyonu ile mevcut matrise satir ve sutun ilave edilebilir
m <- rbind(c(12,26,28),c(25,13,10),c(7,9,11))
m <- rbind(m,c(1,9,4)) # ekleme işlemi # r (row) satır c (column) sütün
m


[,1] [,2] [,3]
[1,] 12   26   28  
[2,] 25   13   10  
[3,]  7    9   11  
[4,]  1    9    4

In [52]:
#vektorleri boyutlandirarak matris elde etme dim()
 d <- c(32,46,73,12,42,46,56,91,77)
dim(d) <-c(3,3)
d


[,1] [,2] [,3]
[1,] 32   12   56  
[2,] 46   42   91  
[3,] 73   46   77

In [53]:
#satir ve sutunlari isimlendirme
#matrix fonksiyonu icinde dimnames parametresi kullanilir
m <- matrix(c(12,17,23,15,46,17,3,45,29),3,dimnames=list(c("I","II","III"), c("A","B","C")))
m

A  B  C 
I   12 15  3
II  17 46 45
III 23 17 29

In [56]:
#bunu yapmanin bir diger seklide
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
rownames(m) <- c("I","II","III") #sutun isimleri
colnames(m) <- c("A","B","C") #satir isimleri
m

A  B  C 
I   12 15  3
II  17 46 45
III 23 17 29

In [57]:
#satir ve sutun isimlerini silelim
dimnames(m) <- list(NULL,NULL)
m

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

In [61]:
#matris elemanina erisim indeksleri kullanacagiz
#matrisler iki boyutlu oldugu icin iki boyutunda indeksini tanimlamaliyiz
#ornegin bir matrisin 2. satir ve sutun 3. sutununda elemana erismek icin [2,3]
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
m[2,3] # 2. satır 3. sütünu göster
m[,3] # 3. sütün
m[1,] # 1. satır

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1] 45

[1]  3 45 29

[1] 12 15  3

In [62]:
#matrisin ilk iki satirini iceren bir alt matris olusturalim
m[1:2,]

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45

In [64]:
m
#matrisin 1 ile 3. satirini ve 2 ile 3. sutunlarini goz onune alalim
m [c(1,3),c(2,3)]

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[,1] [,2]
[1,] 15    3  
[2,] 17   29

In [65]:

#bir kosula uyan matris elemaninin bulunmasi
#ornegin 20 den kucuk olanlari bulalim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
m [m <20]

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1] 12 17 15 17  3

In [66]:
#isimlendirilmis matris elemanlarina erisim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3,dimnames=list(c("I","II","III"), c("A","B","C")))
m
m["I","A"]

A  B  C 
I   12 15  3
II  17 46 45
III 23 17 29

[1] 12

In [67]:
#matrisin sadece sutunlari isimlendirilmis ise bu matrisiN "A", ve "C"sutunlarina bakalim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
colnames(m) <- c("A","B","C")
m

m[,c("A","C")]

A  B  C 
[1,] 12 15  3
[2,] 17 46 45
[3,] 23 17 29

A  C 
[1,] 12  3
[2,] 17 45
[3,] 23 29

In [ ]:
#matris elemanlarinin degistirilmesi
#matrisin elemanlari indeksler kullanilarak degistirilebilir
#ornegin 2. satir 3. sutundaki 45 elemanini 20 olarak degistirelim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m

m[2,3] <- 20
m

In [68]:
#matrisin 3. sutununu topluca 10 yapalim
m[,3] <- 10
m

A  B  C 
[1,] 12 15 10
[2,] 17 46 10
[3,] 23 17 10

In [69]:
#bir koşul tanimalayarak 25 ten kucuk olanlarin yerine 0 atayalim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m

m [m <25] <- 0
m

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[,1] [,2] [,3]
[1,] 0     0    0  
[2,] 0    46   45  
[3,] 0     0   29

In [70]:
#matris elemanlarinin silinmesi
#satir ve sutunlarin elemanlari silinebilir - ile islem yapılır
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
m <- m[-3,] #3. satir silindi
m

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45

In [71]:
#simdi de sutun silelim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
m <- m[,-2] #2. sutun silindi
m


[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[,1] [,2]
[1,] 12    3  
[2,] 17   45  
[3,] 23   29

In [73]:
#iki matrisin birlestirilmesi
m1 <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m1

m2 <- matrix(c(8,5,3,1,6,7,34,43,9),3)
m2
#satirlar bazinda birlestirelim
rbind (m1,m2)
#sutunlar bazinda birlesitirelim
cbind(m1,m2)

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[,1] [,2] [,3]
[1,] 8    1    34  
[2,] 5    6    43  
[3,] 3    7     9

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29  
[4,]  8    1   34  
[5,]  5    6   43  
[6,]  3    7    9

In [74]:
#matrisin en buyuk ve en kucuk elemani
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
max(m)
min(m)


[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1] 46

[1] 3

In [75]:
#spesifik bir sutundan en buyuk elemani bulacaksak.
#mesela 2. sutundan en buyuk eleman
max(m[,2])
min(m[3,]) #3. satirdan en kucuk eleman

[1] 46

[1] 17

In [ ]:
#satir ve sutunlarin toplami
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
sum(m)
#tum sutunlari vektor halinde toplamak icin
colSums(m)
#sutunlarin toplamini tek tek gormek icin
colSums(m)[1]#BİRİNCİ SUTUN TOPLAMİ
colSums(m)[2]#İKİNCİ SUTUN TOPLAMI
colSums(m)[3]#UCUNCU SUTUN TOPLAMI
#ayni sonuca su sekilde de ulasilir
sum(m[,1])#BİRİNCİ SUTUN TOPLAMİ

In [ ]:
#tum satirlari vektor halinde toplamak icin
rowSums(m) # 30 108 69

#satir ve sutun ortalamalari rowMeans colMeans
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
rowMeans(m)
colMeans(m)
mean(m)

In [79]:
## apply fonksiyonu
#apply(matris, kenar, foksiyon)
# matrislere bir fonksiyon ile tanimlanan bir islem uygulamamiz soz konusu ise
#eger satir islemleri yapilacak ise kenar parametresi olarak 1,
#sutun islemleri yapilacak ise kenar parametresi olarak 2 kaydedilir
#ornegin herbir satirin toplamini ayri ayri hesaplayarak bir vektor biciminde goruntulenmek uzere
#sum fonksiyonunu kullanalim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
apply(m,1,sum)



[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1]  30 108  69

In [78]:
#ayni islemi sutunlar uzerinden yapalim
apply(m,2,sum)

#her bir satir icindeki en buyuk degerleri elde etmek icin max parametresi kullanilabilir
apply(m,1,max)

[1] 52 78 77

[1] 15 46 29

In [80]:
#Matrislerle cebirsel islemler
#kosegen islemleri
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
#       [,1]  [,2]  [,3]
#[1,]   *12    15     3
#[2,]    17   *46    45
#[3,]    23    17   *29

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

In [81]:
#matrisin kosegenleri 12,46,29 bu kosegenleri R ile elde edelim
diag(m)
#kosegen elemanlarinin toplamini hesaplayalim
sum(diag(m))

#kosegen degerlerinin tumunu 1 yapalim
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
diag(m) <- 1

[1] 12 46 29

[1] 87

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

In [82]:
#birim matris
#birim matris kosegen elemanlari 1 diger elemanlari 0 olan bir kare matristir
# diag() kosegen fonksiyonu birim matris elde etmek icin kullanalim
m1 <- diag(3)
m1

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [85]:
#matris transpozesi
#bir matrisin transpozesi satirlari ile sutunlarinin yer degistirmesi ile elde edilir
m <- matrix(c(12,17,23,15,46,17,3,45,29),3)
m
#     [,1]  [,2]  [,3]
#[1,]   12   15     3
#[2,]   17   46    45
#[3,]   23   17    29


# t fonskiyonu ile transpozesini bulabiliriz
t(m)
#     [,1] [,2] [,3]
#[1,]   12   17   23
#[2,]   15   46   17
#[3,]    3   45   29

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[,1] [,2] [,3]
[1,] 12   17   23  
[2,] 15   46   17  
[3,]  3   45   29

In [86]:
#matrislerin toplanmasi
m1 <- matrix(c(5,6,3,1,7,2,4,5,2),3,3)
m1

m2 <- matrix(c(12,14,15,26,33,25,17,22,36),3,3)
m2

m1+m2

[,1] [,2] [,3]
[1,] 5    1    4   
[2,] 6    7    5   
[3,] 3    2    2

[,1] [,2] [,3]
[1,] 12   26   17  
[2,] 14   33   22  
[3,] 15   25   36

[,1] [,2] [,3]
[1,] 17   27   21  
[2,] 20   40   27  
[3,] 18   27   38

In [ ]:
#matrisin skaler degerle carpimi
#bir matrisin tum elemanlari ayni sayi ile carpilabilir. ornegin 3 ile carpalim
m1 <- matrix(c(5,6,3,1,7,2,4,5,2),3,3)
m1
3*m1

#matrislerin carpimi
# iki matrisin karsilikli elemanlarinin carpilmasi ile,
#cebirsel anlamda iki matrisin carpilmasi iki farkli olaydir
#iki matrisin carpilabilmesi icin A matrisin satir sayisinin B matrisinin sutun sayisina ESİT olmasi gerekir
m1 <- matrix(c(5,6,3,1,7,2,4,5,2),3,3)
m1

m2 <- matrix(c(12,14,15,26,33,25,17,22,36),3,3)
m2

m1%*%m2

#matris determinanti
a <- matrix(c(5,2,8,1,4,7,7,3,1),3)
a

d <- det(a)
d

#matrisin tersi
m1 <- matrix(c(5,6,3,1,7,2,4,5,2),3,3)
m1

solve(m1)