<a href="https://colab.research.google.com/github/beratkc/Rprogramlama/blob/main/4_hafta.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Listeler
#listeler vektorlere benzer, ancak farkli veri turlerini de barindirir
#liste olusturma list() fonksiyonu ile
list <- list(25) # bir adet sayisal deger içeren liste

In [2]:
lis <- list(25,"A",TRUE) #Liste icinde numerik,karakter ve mantiksal deger
lis #3 farkli deger iceren bir nesnenin gorunumu

[[1]]
[1] 25

[[2]]
[1] "A"

[[3]]
[1] TRUE

In [3]:
# farkli verilerden olusan vektor olusturalim
#bu vektorlerden olusan bir liste yapalim
yas <- c(25,30,28,36)
kan <- c("A","B","O","AB")
sonuc <- c(TRUE,FALSE,FALSE)
lis <- list(yas,kan,sonuc)
lis

[[1]]
[1] 25 30 28 36

[[2]]
[1] "A"  "B"  "O"  "AB"

[[3]]
[1]  TRUE FALSE FALSE

In [4]:
#farkli uc nesnenin bir liste icinde yer almasi
vek <- c(5,7,3,1,0,-1)
df <- data.frame(c(1,2,5),c("A","B","C"))
mat <- matrix(c(12,17,23,15,46,17,3,45,29),3)
lis <- list(vek,df,mat)
lis

[[1]]
[1]  5  7  3  1  0 -1

[[2]]
  c.1..2..5. c..A....B....C..
1          1                A
2          2                B
3          5                C

[[3]]
     [,1] [,2] [,3]
[1,]   12   15    3
[2,]   17   46   45
[3,]   23   17   29

In [5]:
#vektorun liste olmaya zorlanmasi as.list()
isimler <- c("nur","kuban","sevgi")
as.list(isimler)

[[1]]
[1] "nur"

[[2]]
[1] "kuban"

[[3]]
[1] "sevgi"

In [6]:
#bos liste
lis <- vector("list",5)
lis

[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

[[4]]
NULL

[[5]]
NULL

In [7]:
#isimlendirilmis liste uyesleri
vek <- c(5,7,3,1,0,-1)
df <- data.frame(c(1,2,5),c("A","B","C"))
mat <- matrix(c(12,17,23,15,46,17,3,45,29),3)
lis <- list(vek,df,mat)
lis

[[1]]
[1]  5  7  3  1  0 -1

[[2]]
  c.1..2..5. c..A....B....C..
1          1                A
2          2                B
3          5                C

[[3]]
     [,1] [,2] [,3]
[1,]   12   15    3
[2,]   17   46   45
[3,]   23   17   29

In [8]:
#elde edilen liste elemanlari matris olduguna gore herhangi bir elemana ulasmak icin
#indeks kullanilir
lis[[3]][2,3] # 3ün 2. satırın 3 sütunu

[1] 45

In [9]:
#liste dilimleme
#uye indeks numaralari yerine liste uyelerinin isimleri kullanilarak dilimlenmesi
#boylece liste disinda bir kopyasinin olusturulmasi soz konusu olabilir

vek <- c(5,7,3,1,0,-1)
df <- data.frame(c(1,2,5),c("A","B","C"))
mat <- matrix(c(12,17,23,15,46,17,3,45,29),3)
lis <- list(v=vek,d=df,m=mat)
l <- lis["m"]
l

$m
     [,1] [,2] [,3]
[1,]   12   15    3
[2,]   17   46   45
[3,]   23   17   29

In [10]:
#istenirse birden fazla uye dilimlenebilir
l <- lis[c("d","m")]
l

$d
  c.1..2..5. c..A....B....C..
1          1                A
2          2                B
3          5                C

$m
     [,1] [,2] [,3]
[1,]   12   15    3
[2,]   17   46   45
[3,]   23   17   29

In [13]:
#uyelere erisim
#isimlendirilmis uyelere sahip bir listede bir uyeye ulasmak icin uye ismini kullanmak gerekebilir
#lis isimli listenin "m" isimli uyelerine erisim saglayalim
vek <- c(5,7,3,1,0,-1)
df <- data.frame(c(1,2,5),c("A","B","C"))
mat <- matrix(c(12,17,23,15,46,17,3,45,29),3)
lis <- list(v=vek,d=df,m=mat)
l <- lis["m"]


$m
     [,1] [,2] [,3]
[1,]   12   15    3
[2,]   17   46   45
[3,]   23   17   29

In [19]:
#ayni amaca ulasmak icin uye isnmini $ operatoru ile birlikte kullanabiliriz
lis$m

#uye isimlerini kullanarak bu uyenin bir elemanina ulasilabilir
#ornegin "m" isimli matrisin [2,2]] elemanini eldeetmek icin lis$m tanimina
#soz konusu matrisin elemani eklenir
lis$m[2,2]

[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1] 46

In [20]:
#liste isimlerinin dogrudan kullanimi
#uyelere liste adi belirlemeden ulasmak icin attach() fonksiyonu
attach(lis)
m
v

The following objects are masked from lis (pos = 3):

    d, m, v


The following objects are masked from lis (pos = 4):

    d, m, v


The following objects are masked from lis (pos = 5):

    d, m, v


The following objects are masked from lis (pos = 6):

    d, m, v




[,1] [,2] [,3]
[1,] 12   15    3  
[2,] 17   46   45  
[3,] 23   17   29

[1]  5  7  3  1  0 -1

In [21]:
#liste uzerinde islemler
#listeye uye ekleme
#once liste olusturalim
vek <- c(5,7,3,1,0,-1)
lis <- list(v=vek)
lis

$v
[1]  5  7  3  1  0 -1

In [22]:
#olusturulan bu listeye v1 isimli yeni bir vektor uyesi daha eklenmek istemektedir
#bu eklenen listenin 2. uyesi olacaktir
lis[[2]] <- c(-2,4,6)
lis

$v
[1]  5  7  3  1  0 -1

[[2]]
[1] -2  4  6

In [25]:
#bu listenin herhangi bir uyesine ulasmak icin uye isimlerini kullanabilecegimize gore
#$ operatoru kullanilarak bir uyesinin degerini degistirmek mumkundur
#ornegin yukarida en son yapilan islemlerin yerine bu kez lis$v1 erisim bilgisi kullalim
vek <- c(5,7,3,1,0,-1)
lis <- list(v=vek)
lis
lis$v1 <- c(-2,4,6)
lis

$v
[1]  5  7  3  1  0 -1

$v
[1]  5  7  3  1  0 -1

$v1
[1] -2  4  6

In [26]:
#listedeki bir uyeyi silme
#bir liste olusturulduktan sonra istenen uyeyi silmek mumkundur

lis[[2]] <- NULL
lis

$v
[1]  5  7  3  1  0 -1

In [27]:
#liste uyesinin ismini kullanarak da silmek mumkundur
lis$v1 <- NULL
lis

$v
[1]  5  7  3  1  0 -1

In [28]:
#listenin bir uyesini guncelleme
#listenin herhangi bir uyesini guncellemek mumkundur

vek <- c(5,7,3,1,0,-1)
df <- data.frame(sira=c(1,2,5),kod=c("A","B","C"))
mat <- matrix(c(12,17,23,15,46,17,3,45,29),3)
lis <- list(v=vek,d=df,m=mat)
lis

$v
[1]  5  7  3  1  0 -1

$d
  sira kod
1    1   A
2    2   B
3    5   C

$m
     [,1] [,2] [,3]
[1,]   12   15    3
[2,]   17   46   45
[3,]   23   17   29

In [29]:
#bir listenin "v" isimli vektorunun 3. elemanini "15 olarak,
#"d" isimli veri cercevesinin ise [3,1] elamanini "3 olarak
#"m" isimli matris uyesinin [1,1] elemanini 10 olarak degistirmek icin
lis$v[3] <- 15
lis$d[3,1] <- 3
lis$m[1,1] <-10
lis


$v
[1]  5  7 15  1  0 -1

$d
  sira kod
1    1   A
2    2   B
3    3   C

$m
     [,1] [,2] [,3]
[1,]   10   15    3
[2,]   17   46   45
[3,]   23   17   29

In [31]:
#ayni amaca su sekilde de ulasilir
lis[[1]][3] <-15
lis[[2]] [3,1] <-3
lis[[3]][1,1] <-10